### PR TITLE
Migrate to Node 20, bump actions to latest versions

### PR DESCRIPTION
**Pull request by emanuelgaspar**

### CODE REVIEW

**Comment by emanuelgaspar** [comment]
Test works: https://github.com/trakx/historical-prices/actions/runs/7643111087/job/20824342998

**Comment by emanuelgaspar** [comment]
Nuget works: https://github.com/trakx/historical-prices/actions/runs/7643249207/job/20824815605

**Comment by emanuelgaspar** [comment]
Deploy still throws warnings:
<https://github.com/trakx/historical-prices/actions/runs/7643614117>

Deploy relies on `chrnorm/deployment-action@v2.0.5` and `chrnorm/deployment-status@v2.0.1` which haven't been updated in a long time. I checked the repos and there's not even an issue raised to update them to Node 20. We should look into replacing these at some point soon-ish.

**Review by joaofbvieira — APPROVED** [review]
LGTM. Btw, any breaking change, specially in the major upgrades?

**Review by TiagoFroisPereira — APPROVED** [review]

**Review by goneneren — APPROVED** [review]

**Pull request merged**
